In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Load datasets
auction = pd.read_csv('/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/ipl_2022_dataset.csv')
stats = pd.read_csv('/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/IPL_Data.csv')

In [ ]:
# Preview
auction.head()

,Index,Player,Base Price,TYPE,COST IN (CR.),Cost IN $ (000),Team
0,0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,Gujarat Titans
1,1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,Gujarat Titans
2,2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,Gujarat Titans
3,3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,Gujarat Titans
4,4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,Gujarat Titans

In [ ]:
stats.head()

,Name,Team,Url,Type,ValueinCR,Full Name,Born,Age,National Side,Batting Style,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,Mayank Agarwal,PBKS,https://sports.ndtv.com/cricket/players/1430-m...,Batsman,12.00,Mayank Anurag Agarwal,"February 16, 1991 Bangalore, Karnataka","31 Years, 0 Months, 28 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Liam Livingstone,PBKS,https://sports.ndtv.com/cricket/players/64363-...,All-Rounder,11.50,Liam Stephen Livingstone,"August 4, 1993 Barrow-in-Furness, Cumberland","28 Years, 7 Months, 11 Days",England,Right Handed,...,0.0,13.0,0.0,0/13 v MI,0.0,0.0,NaN,13.00,NaN,1.0
2,Kagiso Rabada,PBKS,https://sports.ndtv.com/cricket/players/64042-...,Bowler,9.25,Kagiso Rabada,"May 25, 1995 Johannesburg","26 Years, 9 Months, 22 Days",South Africa,Left Handed,...,2.0,1560.0,76.0,4/21 v RCB,4.0,0.0,20.52,8.21,15.0,50.0
3,Shahrukh Khan,PBKS,https://sports.ndtv.com/cricket/players/113433...,All-Rounder,9.00,Masood Shahrukh Khan,"May 27, 1995 Chennai, Tamil Nadu","26 Years, 9 Months, 20 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Shikhar Dhawan,PBKS,https://sports.ndtv.com/cricket/players/737-sh...,Batsman,8.25,Shikhar Dhawan,"December 5, 1985 Delhi","36 Years, 3 Months, 10 Days",India,Left Handed,...,0.0,66.0,4.0,1/7 v DC,0.0,0.0,16.50,8.25,12.0,6.0

In [ ]:
# Standardize player names in both
auction['Player'] = auction['Player'].str.lower().str.strip()
stats['Name'] = stats['Name'].str.lower().str.strip()

In [ ]:
# Rename for merging clarity
auction.rename(columns={
    'Player': 'Name',        # so both files have 'Name'
    'TYPE': 'Role_Auction',  # rename role column from auction
    'COST IN (CR.)': 'Price_Cr'
}, inplace=True)

stats.rename(columns={
    'Type': 'Role_Stats'     # rename role column from stats
}, inplace=True)

# Merge on 'Name'
merged = pd.merge(auction, stats, on='Name', how='inner')

In [ ]:
# Path to your project folder in Drive
path = '/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/Merged_data.csv'

# Save merged CSV there
merged.to_csv(path, index=False)
merged.head()

,Index,Name,Base Price,Role_Auction,Price_Cr,Cost IN $ (000),Team_x,Team_y,Url,Role_Stats,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,0,rashid khan,Draft Pick,BOWLER,15.0,1950.0,Gujarat Titans,GT,https://sports.ndtv.com/cricket/players/107477...,Bowler,...,4.0,1912.0,93.0,3/7 v DC,10.0,0.0,20.55,6.33,19.48,76.0
1,1,hardik pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,Gujarat Titans,GT,https://sports.ndtv.com/cricket/players/64177-...,All-Rounder,...,0.0,1313.0,42.0,3/20 v CSK,3.0,0.0,31.26,9.06,20.69,60.0
2,2,lockie ferguson,2 Cr,BOWLER,10.0,1300.0,Gujarat Titans,GT,https://sports.ndtv.com/cricket/players/64149-...,Bowler,...,1.0,648.0,24.0,3/15 v SRH,2.0,0.0,27.00,8.11,19.95,22.0
3,3,rahul tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,Gujarat Titans,GT,https://sports.ndtv.com/cricket/players/64845-...,All-Rounder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,shubman gill,Draft Pick,BATTER,8.0,1040.0,Gujarat Titans,GT,https://sports.ndtv.com/cricket/players/108578...,Batsman,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Drop unnecessary/duplicate columns
merged.drop(columns=['Index', 'Team_y'], inplace=True)

# Rename Team_x to just Team
merged.rename(columns={'Team_x': 'Team'}, inplace=True)

In [ ]:
# Avoid divide-by-zero
merged['RunsScored'] = merged['RunsScored'].replace(0, 1)
merged['Wickets'] = merged['Wickets'].replace(0, 1)

# Cost KPIs
merged['Cost_per_Run'] = merged['Price_Cr'] / merged['RunsScored']
merged['Cost_per_Wicket'] = merged['Price_Cr'] / merged['Wickets']

# ROI formula: You can adjust weights here
merged['ROI'] = ((merged['RunsScored'] * 0.5) + (merged['Wickets'] * 25)) / merged['Price_Cr']

# Round
merged[['Cost_per_Run', 'Cost_per_Wicket', 'ROI']] = merged[['Cost_per_Run', 'Cost_per_Wicket', 'ROI']].round(2)

merged.to_csv('/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/Merged_data.csv', index=False)

In [ ]:
# Check for null values in each column
merged.isnull().sum().sort_values(ascending=False)

S/R                118
BowlingAVG         118
ROI                108
Best               101
EconomyRate        101
3s                 101
Cost_per_Wicket    101
Mtc                101
Maidens            101
5s                 101
RunsConceded       101
Overs              101
Wickets            101
InningsBowled      101
Sport               98
StumpingsMade       79
CatchesTaken        79
BattingAVG          78
Cost_per_Run        71
HighestInnScore     71
RunsScored          71
Ducks               65
R/O                 65
BattingS/R          64
NotOuts             64
50s                 64
100s                64
InningsBatted       64
4s                  64
MatchPlayed         64
6s                  64
Bowling             28
Batting Style        9
Full Name            6
Born                 6
National Side        6
Age                  6
Role_Stats           0
Name                 0
Url                  0
ValueinCR            0
Base Price           0
Role_Auction         0
Price_Cr             0
Cost IN $ (000)      0
Team                 0
dtype: int64

In [ ]:
fill_zero_cols = [
    'RunsScored', 'Wickets', 'Overs', 'RunsConceded', 'InningsBowled',
    'Maidens', 'Mtc', '3s', '5s', 'CatchesTaken', 'StumpingsMade',
    'Ducks', '4s', '6s', '100s', '50s', 'NotOuts', 'InningsBatted',
    'MatchPlayed'
]

for col in fill_zero_cols:
    if col in merged.columns:
        merged[col] = merged[col].fillna(0)

In [ ]:
drop_cols = ['Full Name', 'Born', 'Age', 'Batting Style', 'Bowling', 'Url']
merged.drop(columns=drop_cols, inplace=True)

In [ ]:
# Fill BattingAVG & BattingS/R for batsmen/all-rounders
merged.loc[merged['Role_Stats'].isin(['Batsman', 'All-Rounder']), 'BattingAVG'] = merged.loc[merged['Role_Stats'].isin(['Batsman', 'All-Rounder']), 'BattingAVG'].fillna(merged['BattingAVG'].mean())
merged.loc[merged['Role_Stats'].isin(['Batsman', 'All-Rounder']), 'BattingS/R'] = merged.loc[merged['Role_Stats'].isin(['Batsman', 'All-Rounder']), 'BattingS/R'].fillna(merged['BattingS/R'].mean())

# Fill BowlingAVG & Economy for bowlers/all-rounders
merged.loc[merged['Role_Stats'].isin(['Bowler', 'All-Rounder']), 'BowlingAVG'] = merged.loc[merged['Role_Stats'].isin(['Bowler', 'All-Rounder']), 'BowlingAVG'].fillna(merged['BowlingAVG'].mean())
merged.loc[merged['Role_Stats'].isin(['Bowler', 'All-Rounder']), 'EconomyRate'] = merged.loc[merged['Role_Stats'].isin(['Bowler', 'All-Rounder']), 'EconomyRate'].fillna(merged['EconomyRate'].mean())
merged.loc[merged['Role_Stats'].isin(['Bowler', 'All-Rounder']), 'S/R'] = merged.loc[merged['Role_Stats'].isin(['Bowler', 'All-Rounder']), 'S/R'].fillna(merged['S/R'].mean())

merged.to_csv('/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/Merged_data.csv', index=False)

In [ ]:
# Drop unnecessary columns
merged.drop(columns=['Sport', 'Best', 'R/O', 'HighestInnScore'], inplace=True)

# Fill 'National Side'
merged['National Side'] = merged['National Side'].fillna('Unknown')

In [ ]:
merged['Cost_per_Run'] = merged['Price_Cr'] / merged['RunsScored'].replace(0, 1)
merged['Cost_per_Wicket'] = merged['Price_Cr'] / merged['Wickets'].replace(0, 1)
merged['ROI'] = ((merged['RunsScored'] * 0.5) + (merged['Wickets'] * 25)) / merged['Price_Cr']

merged[['Cost_per_Run', 'Cost_per_Wicket', 'ROI']] = merged[['Cost_per_Run', 'Cost_per_Wicket', 'ROI']].round(2)

In [ ]:
merged[['BattingAVG', 'BattingS/R', 'BowlingAVG', 'EconomyRate', 'S/R']] = (
    merged[['BattingAVG', 'BattingS/R', 'BowlingAVG', 'EconomyRate', 'S/R']].fillna(0)
)
merged.to_csv('/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/Merged_data.csv', index=False)
merged.isnull().sum().sort_values(ascending=False)

Name               0
Base Price         0
Role_Auction       0
Price_Cr           0
Cost IN $ (000)    0
Team               0
Role_Stats         0
ValueinCR          0
National Side      0
MatchPlayed        0
InningsBatted      0
NotOuts            0
RunsScored         0
100s               0
50s                0
4s                 0
6s                 0
BattingAVG         0
BattingS/R         0
CatchesTaken       0
StumpingsMade      0
Ducks              0
InningsBowled      0
Overs              0
Maidens            0
RunsConceded       0
Wickets            0
3s                 0
5s                 0
BowlingAVG         0
EconomyRate        0
S/R                0
Mtc                0
Cost_per_Run       0
Cost_per_Wicket    0
ROI                0
dtype: int64

In [ ]:
# Add unique ID
merged.insert(0, 'Player_ID', range(1, len(merged) + 1))
merged.to_csv('/content/drive/MyDrive/IPL Auction vs Player Performance Analysis using Python and Power BI/Merged_data.csv', index=False)